import Head from 'next/head'

import styles from '../styles/Home.module.css'
// console.log(`styles`, styles)


import Content from '../components/Content'
import Layout from '../components/Layout'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout Content={<Content />} Footer={<Footer />} />


    </div >
  )
}
